version: '2'
services:
  database:
    image: mysql 
    ports:
       - "3306:3306"
    volumes:
       - ./config/gfdbdump.sql:/docker-entrypoint-initdb.d/gfdbdump.sql
    environment:
        MYSQL_ROOT_PASSWORD: toortoor
        MYSQL_USER: root
        MYSQL_PASSWORD: toortoor
        MYSQL_DATABASE: sv_crm
  webapp:
    depends_on:
        - database 
    build: .
    ports:
        - "8080:8080"
    links:
        - database:mysql
  reverseproxy:
    depends_on:
        - webapp
    image: "nginx"
    volumes:
        - ./config/nginx.conf:/etc/nginx/nginx.conf
        # You should change the host mount paths for the following two entries to the appropriate location of 
        # your Let's Encrypt key files
        - /sv_crm/certs/gopherfacecert.pem
        - /sv_crm/certs/gopherfacekey.pem
    ports:
        - "80:80"
        - "443:443"